common: &common
  adapter: postgresql
  encoding: unicode
  username: postgres

development:
  <<: *common
  database: letshire_development

test:
  <<: *common
  database: letshire_test

production:
  <<: *common
  database: letshire_production

