localcommon: &localcommon
  adapter: sqlite3
  pool: 5
  timeout: 5000

common: &common
  adapter: postgresql
  encoding: unicode
  username: postgres

test:
  <<: *localcommon
  database: db/test.sqlite3

development:
  <<: *common
  database: letshire_development

ci:
  <<: *common
  database: letshire_ci

production:
  <<: *common
  database: letshire_production
